### ISSUE TITLE
Error with History version in React-router

### ISSUE THREAD

**Issue by markmichon** [fullstackreact/react-yelp-clone#11]
Upon `npm install`, there seems to be an problem where the included version of react-router requires a pre-3.0 version of history, yet history 3.0 is installed.

**Comment by henrylingumi** [comment]
@markmichon might be a bit of a silly question, but what's the best way of solving this?

**Comment by markmichon** [comment]
@henrylingumi I'm unsure if it breaks anything else, which is why I haven't put forth a pr for it, but completely removing 3.0 of history and instead requiring/installing the version that shows up in the error worked for me in the limited testing that I did.

**Comment by auser** [comment]
For now (until react-router is updated), install the `2.1.2` version:

``` bash
npm install --save history@2.1.2
```
