### ISSUE TITLE
blank screen on win 10 and osx

### ISSUE THREAD

**Issue by yardennis** [fullstackreact/react-yelp-clone#22]
tried installing on win 10 / osx with node 6 and node 8

can npm install and npm start

localhost:3000 returned title but with blank screen

is there a need to update for latest node or packages for win 10 / osx ?

Thanks

**Comment by yardennis** [comment]
got it working using yarn and yarn start
 but after selecting a shop the images are just placeholder

**Comment by paulywill** [comment]
> got it working using yarn and yarn start
> but after selecting a shop the images are just placeholder

This should be changed on the Readme!
