### ISSUE TITLE
Include Mention of SET NODE_ENV=development for Windows Users

### ISSUE THREAD

**Issue by EmmaRamirez** [fullstackreact/react-yelp-clone#3]
It might be helpful to include somewhere that for Windows users, their npm start script should be `SET NODE_ENV=development ./node_modules/.bin/hjs-dev-server`, otherwise they get a message that the variable doesn't exist.

**Comment by slevr** [comment]
A different way to handle is to go with something like:

`npm i cross-env --save-dev`

then change package.json start script to:

`"cross-env NODE_ENV=development hjs-dev-server"`

**Comment by ChucklesStern** [comment]
Great catch Emma! Have you been able to get the app to run in Windows AT ALL? 

I cloned the repo and followed all directions and am still getting the following error: 
`var https = serverConfig.https
                        ^

TypeError: Cannot read property 'https' of undefined
` clearly **this webpack config isn't for Windows Users.** 

and that is AFTER having to use SET Node_Env like as you mention.

Ari would love some clarity on this at your soonest.

**Comment by auser** [comment]
@ChucklesStern @insin provided a patch. It has been included in the latest push. Apologies for the delay!
